// BASE DE DATOS
const dbItems = [
    // Categoría de Nodos

        { id: 0, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 2, nombre: "Piedra de diamante", tipo: "Nodo" },
        { id: 4, nombre: "Piedra rubí", tipo: "Nodo" },
        { id: 6, nombre: "Piedra de jade", tipo: "Nodo" },
        { id: 8, nombre: "Piedra de amatista", tipo: "Nodo" },
        { id: 10, nombre: "Piedra de topacio", tipo: "Nodo" },
        { id: 12, nombre: "Piedra esmeralda", tipo: "Nodo" },
        { id: 14, nombre: "Piedra aguamarina", tipo: "Nodo" },
        { id: 25, nombre: "Piedra de moscovita", tipo: "Nodo" },
        { id: 32, nombre: "Piedra", tipo: "Nodo" },
        { id: 34, nombre: "Piedra", tipo: "Nodo" },
        { id: 36, nombre: "Piedra", tipo: "Nodo" },
        { id: 38, nombre: "Piedra", tipo: "Nodo" },
        { id: 40, nombre: "Piedra", tipo: "Nodo" },
        { id: 42, nombre: "Piedra", tipo: "Nodo" },
        { id: 44, nombre: "Piedra preciosa", tipo: "Nodo" },
        { id: 46, nombre: "Piedra mística", tipo: "Nodo" },
        { id: 48, nombre: "Piedra nevada", tipo: "Nodo" },
        { id: 50, nombre: "Piedra nevada", tipo: "Nodo" },
        { id: 52, nombre: "Piedra nevada", tipo: "Nodo" },
        { id: 54, nombre: "Piedra nevada", tipo: "Nodo" },
        { id: 56, nombre: "Piedra nevada", tipo: "Nodo" },
        { id: 58, nombre: "Piedra nevada", tipo: "Nodo" },
        { id: 75, nombre: "Piedra geoda", tipo: "Nodo" },
        { id: 76, nombre: "Piedra geoda congelada", tipo: "Nodo" },
        { id: 77, nombre: "Piedra geoda de magma", tipo: "Nodo" },
        { id: 81, nombre: "Piedra radiactiva", tipo: "Nodo" },
        { id: 290, nombre: "Piedra de hierro", tipo: "Nodo" },
        { id: 313, nombre: "Tronco", tipo: "Nodo" },
        { id: 314, nombre: "Muñón", tipo: "Nodo" },
        { id: 315, nombre: "Muñón", tipo: "Nodo" },
        { id: 316, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 317, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 318, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 319, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 320, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 321, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 331, nombre: "Cristal de hielo", tipo: "Nodo" },
        { id: 332, nombre: "Cristal de hielo", tipo: "Nodo" },
        { id: 333, nombre: "Cristal de hielo", tipo: "Nodo" },
        { id: 430, nombre: "Piedra", tipo: "Nodo" },
        { id: 432, nombre: "Piedra", tipo: "Nodo" },
        { id: 447, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 450, nombre: "Piedra", tipo: "Nodo" },
        { id: 631, nombre: "Piedra", tipo: "Nodo" },
        { id: 633, nombre: "Piedra", tipo: "Nodo" },
        { id: 674, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 675, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 676, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 677, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 678, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 679, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 784, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 792, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 793, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 794, nombre: "Malas hierbas", tipo: "Nodo" },
        { id: 816, nombre: "Fósil de cráneo", tipo: "Nodo" },
        { id: 817, nombre: "Fósil de cráneo", tipo: "Nodo" },
        { id: 818, nombre: "Fósil de cráneo", tipo: "Nodo" },
        { id: 819, nombre: "Fósil de cráneo", tipo: "Nodo" },
        { id: 820, nombre: "Fósil de fragmento de hueso", tipo: "Nodo" },
        { id: 821, nombre: "Fósil de fragmento de hueso", tipo: "Nodo" },
        { id: 822, nombre: "Fósil de fragmento de hueso", tipo: "Nodo" },
        { id: 843, nombre: "Piedra de oro", tipo: "Nodo" },
        { id: 844, nombre: "Piedra de oro", tipo: "Nodo" },
        { id: 845, nombre: "Piedra de oro", tipo: "Nodo" },
        { id: 846, nombre: "Piedra de oro", tipo: "Nodo" },
        { id: 847, nombre: "Piedra de oro", tipo: "Nodo" },
        { id: 849, nombre: "Piedra de cobre", tipo: "Nodo" },
        { id: 850, nombre: "Piedra de cobre", tipo: "Nodo" },
        { id: 911, nombre: "Menas de iridio", tipo: "Nodo" },
        { id: 912, nombre: "Menas de iridio", tipo: "Nodo" },
        { id: "VolcanoGoldNode", nombre: "Piedra de oro (Volcán)", tipo: "Nodo" },
        { id: "VolcanoCinderNode0", nombre: "Piedra de fragmento de ceniza", tipo: "Nodo" },
        { id: "VolcanoCinderNode1", nombre: "Piedra de fragmento de ceniza", tipo: "Nodo" },
        { id: "CrabPotNode", nombre: "Piedra (Trampa para cangrejos)", tipo: "Nodo" },
        { id: "IridiumNode", nombre: "Menas de iridio", tipo: "Nodo" },
        { id: "CopperNode", nombre: "Menas de cobre", tipo: "Nodo" },
        { id: "IronNode", nombre: "Menas de hierro", tipo: "Nodo" },
        { id: "GoldNode", nombre: "Menas de oro", tipo: "Nodo" },


    // Categoría de Objetos Básicos

{ id: 16, nombre: "Rábano silvestre", tipo: "Basico" },
{ id: 18, nombre: "Narciso", tipo: "Basico" },
{ id: 20, nombre: "Puerro", tipo: "Basico" },
{ id: 22, nombre: "Diente de león", tipo: "Basico" },
{ id: 24, nombre: "Chirivía", tipo: "Basico" },
{ id: 30, nombre: "Recolector", tipo: "Basico" },
{ id: 78, nombre: "Zanahoria cavernaria", tipo: "Basico" },
{ id: 88, nombre: "Coco", tipo: "Basico" },
{ id: 90, nombre: "Fruta del cactus", tipo: "Basico" },
{ id: 91, nombre: "Plátano", tipo: "Basico" },
{ id: 92, nombre: "Savia", tipo: "Basico" },
{ id: 174, nombre: "Huevo grande (Blanco)", tipo: "Basico" },
{ id: 176, nombre: "Huevo (Blanco)", tipo: "Basico" },
{ id: 178, nombre: "Huevo (Marrón)", tipo: "Basico" },
{ id: 180, nombre: "Huevo grande (Marrón)", tipo: "Basico" },
{ id: 182, nombre: "Leche grande", tipo: "Basico" },
{ id: 184, nombre: "Leche", tipo: "Basico" },
{ id: 186, nombre: "Leche de cabra grande", tipo: "Basico" },
{ id: 188, nombre: "Leche de cabra", tipo: "Basico" },
{ id: 192, nombre: "Patata", tipo: "Basico" },
{ id: 194, nombre: "Huevo sombrío", tipo: "Basico" },
{ id: 196, nombre: "Coliflor", tipo: "Basico" },
{ id: 198, nombre: "Col rizada", tipo: "Basico" },
{ id: 200, nombre: "Ruibarbo", tipo: "Basico" },
{ id: 202, nombre: "Col china", tipo: "Basico" },
{ id: 204, nombre: "Ajo", tipo: "Basico" },
{ id: 206, nombre: "Chilaba", tipo: "Basico" },
{ id: 208, nombre: "Melón", tipo: "Basico" },
{ id: 210, nombre: "Tomate", tipo: "Basico" },
{ id: 212, nombre: "Arándano", tipo: "Basico" },
{ id: 214, nombre: "Col lombarda", tipo: "Basico" },
{ id: 216, nombre: "Maíz", tipo: "Basico" },
{ id: 218, nombre: "Carambola", tipo: "Basico" },
{ id: 220, nombre: "Berenjena", tipo: "Basico" },
{ id: 222, nombre: "Alcachofa", tipo: "Basico" },
{ id: 224, nombre: "Calabaza", tipo: "Basico" },
{ id: 226, nombre: "Baya de gema dulce", tipo: "Basico" },
{ id: 228, nombre: "Remolacha", tipo: "Basico" },
{ id: 230, nombre: "Semilla de girasol", tipo: "Basico" },
{ id: 232, nombre: "Baya de nieve", tipo: "Basico" },
{ id: 234, nombre: "Ñame", tipo: "Basico" },
{ id: 236, nombre: "Baya de cristal", tipo: "Basico" },
{ id: 238, nombre: "Crocus", tipo: "Basico" },
{ id: 240, nombre: "Mora", tipo: "Basico" },
{ id: 242, nombre: "Champiñón", tipo: "Basico" },
{ id: 296, nombre: "Salmón", tipo: "Basico" },
{ id: 300, nombre: "Uva", tipo: "Basico" },
{ id: 304, nombre: "Lúpulo", tipo: "Basico" },
{ id: 306, nombre: "Amaranto", tipo: "Basico" },
{ id: 308, nombre: "Arándano rojo", tipo: "Basico" },
{ id: 330, nombre: "Arcilla", tipo: "Basico" },
{ id: 334, nombre: "Barra de cobre", tipo: "Basico" },
{ id: 335, nombre: "Barra de hierro", tipo: "Basico" },
{ id: 336, nombre: "Barra de oro", tipo: "Basico" },
{ id: 337, nombre: "Barra de iridio", tipo: "Basico" },
{ id: 338, nombre: "Cuarzo refinado", tipo: "Basico" },
{ id: 340, nombre: "Miel", tipo: "Basico" },
{ id: 342, nombre: "Mayonesa", tipo: "Basico" },
{ id: 344, nombre: "Mayonesa de pato", tipo: "Basico" },
{ id: 346, nombre: "Cerveza", tipo: "Basico" },
{ id: 348, nombre: "Vino", tipo: "Basico" },
{ id: 350, nombre: "Jugo", tipo: "Basico" },
{ id: 376, nombre: "Amapola", tipo: "Basico" },
{ id: 382, nombre: "Carbón", tipo: "Basico" },
{ id: 388, nombre: "Madera", tipo: "Basico" },
{ id: 390, nombre: "Piedra", tipo: "Basico" },
{ id: 392, nombre: "Concha de nautilo", tipo: "Basico" },
{ id: 393, nombre: "Coral", tipo: "Basico" },
{ id: 394, nombre: "Concha de arcoíris", tipo: "Basico" },
{ id: 396, nombre: "Baya picante", tipo: "Basico" },
{ id: 397, nombre: "Erizo de mar", tipo: "Basico" },
{ id: 399, nombre: "Cebolleta silvestre", tipo: "Basico" },
{ id: 400, nombre: "Guisante de olor", tipo: "Basico" },
{ id: 401, nombre: "Arándano silvestre", tipo: "Basico" },
{ id: 402, nombre: "Avellana", tipo: "Basico" },
{ id: 404, nombre: "Seta común", tipo: "Basico" },
{ id: 406, nombre: "Ciruela silvestre", tipo: "Basico" },
{ id: 412, nombre: "Raíz de invierno", tipo: "Basico" },
{ id: 414, nombre: "Fruta de cristal", tipo: "Basico" },
{ id: 420, nombre: "Champiñón rojo", tipo: "Basico" },
{ id: 422, nombre: "Champiñón morado", tipo: "Basico" },
{ id: 424, nombre: "Queso", tipo: "Basico" },
{ id: 426, nombre: "Queso de cabra", tipo: "Basico" },
{ id: 428, nombre: "Tela", tipo: "Basico" },
{ id: 430, nombre: "Trufa", tipo: "Basico" },
{ id: 432, nombre: "Aceite de trufa", tipo: "Basico" },
{ id: 433, nombre: "Grano de café", tipo: "Basico" },
{ id: 434, nombre: "Fruta estrellada", tipo: "Basico" },
{ id: 440, nombre: "Lana", tipo: "Basico" },
{ id: 442, nombre: "Huevo de pato", tipo: "Basico" },
{ id: 444, nombre: "Pluma de pato", tipo: "Basico" },
{ id: 446, nombre: "Pata de conejo", tipo: "Basico" },
{ id: 593, nombre: "Tulipán", tipo: "Basico" },
{ id: 597, nombre: "Jazmín azul", tipo: "Basico" },
{ id: 709, nombre: "Madera noble", tipo: "Basico" },
{ id: 724, nombre: "Jarabe de arce", tipo: "Basico" },
{ id: 725, nombre: "Resina de roble", tipo: "Basico" },
{ id: 726, nombre: "Brea de pino", tipo: "Basico" },
{ id: 766, nombre: "Baba", tipo: "Basico" },
{ id: 767, nombre: "Ala de murciélago", tipo: "Basico" },
{ id: 768, nombre: "Esencia solar", tipo: "Basico" },
{ id: 769, nombre: "Esencia del vacío", tipo: "Basico" },
{ id: 770, nombre: "Fibra", tipo: "Basico" },
{ id: 771, nombre: "Carne salvaje", tipo: "Basico" },
{ id: 812, nombre: "Hueva", tipo: "Basico" },
{ id: 814, nombre: "Hueva encurtida", tipo: "Basico" },
{ id: 815, nombre: "Té", tipo: "Basico" },
{ id: 829, nombre: "Jengibre", tipo: "Basico" },
{ id: 831, nombre: "Taro", tipo: "Basico" },
{ id: 832, nombre: "Piña", tipo: "Basico" },
{ id: 834, nombre: "Mango", tipo: "Basico" },
{ id: 848, nombre: "Fragmento de ceniza", tipo: "Basico" },
{ id: 851, nombre: "Magma", tipo: "Basico" },
{ id: 852, nombre: "Diente de dragón", tipo: "Basico" },
{ id: 908, nombre: "Cebo mágico", tipo: "Basico" },
{ id: 909, nombre: "Mineral radiactivo", tipo: "Basico" },
{ id: 910, nombre: "Barra radiactiva", tipo: "Basico" },
{ id: 913, nombre: "Enriquecedor", tipo: "Basico" },
{ id: 915, nombre: "Boquilla de presión", tipo: "Basico" },
{ id: 917, nombre: "Condimento Qi", tipo: "Basico" },
{ id: 918, nombre: "Hipervelocidad-Gro", tipo: "Basico" },
{ id: 919, nombre: "Fertilizante de lujo", tipo: "Basico" },
{ id: 928, nombre: "Huevo de oro", tipo: "Basico" },
{ id: "FarAwayStone", nombre: "Piedra lejana", tipo: "Basico" },
{ id: "CalicoEgg", nombre: "Huevo Calico", tipo: "Basico" },
{ id: "Caja Misteriosa", nombre: "Caja misteriosa", tipo: "Basico" },
{ id: "DeluxeBait", nombre: "Cebo de lujo", tipo: "Basico" },
{ id: "Musgo", nombre: "Musgo", tipo: "Basico" },
{ id: "SonarBobber", nombre: "Sonar Bobber", tipo: "Basico" },
{ id: "MysticSyrup", nombre: "Jarabe místico", tipo: "Basico" },
{ id: "StardropTea", nombre: "Té Stardrop", tipo: "Basico" },
{ id: "Boleto de premio", nombre: "Boleto de premio", tipo: "Basico" },
{ id: "ChallengeBait", nombre: "Cebo de desafío", tipo: "Basico" },
{ id: "Zanahoria", nombre: "Zanahoria", tipo: "Basico" },
{ id: "Calabaza de verano", nombre: "Calabaza de verano", tipo: "Basico" },
{ id: "Brócoli", nombre: "Brócoli", tipo: "Basico" },
{ id: "Pescado ahumado", nombre: "Pescado ahumado", tipo: "Basico" },
{ id: "Polvo de mariposa", nombre: "Polvo de mariposa", tipo: "Basico" },
{ id: "Licencia para mascotas", nombre: "Licencia para mascotas", tipo: "Basico" },

   // CATEGORÍA de Fabricables

{ id: 93, nombre: "Antorcha", tipo: "Fabricable" },
{ id: 94, nombre: "Antorcha espiritual", tipo: "Fabricable" },
{ id: 261, nombre: "Tótem de distorsión: Desierto", tipo: "Fabricable" },
{ id: 286, nombre: "Bomba de cereza", tipo: "Fabricable" },
{ id: 287, nombre: "Bomba", tipo: "Fabricable" },
{ id: 288, nombre: "Megabomba", tipo: "Fabricable" },
{ id: 297, nombre: "Semilla de pasto", tipo: "Fabricable" },
{ id: 298, nombre: "Piso de ladrillo", tipo: "Fabricable" },
{ id: 301, nombre: "Iniciador de tipo planta", tipo: "Fabricable" },
{ id: 305, nombre: "Valla de madera dura", tipo: "Fabricable" },
{ id: 309, nombre: "Bellota", tipo: "Fabricable" },
{ id: 310, nombre: "Semilla de arce", tipo: "Fabricable" },
{ id: 311, nombre: "Piña de pino", tipo: "Fabricable" },
{ id: 322, nombre: "Valla de madera", tipo: "Fabricable" },
{ id: 323, nombre: "Valla de piedra", tipo: "Fabricable" },
{ id: 324, nombre: "Valla de hierro", tipo: "Fabricable" },
{ id: 325, nombre: "Puerta", tipo: "Fabricable" },
{ id: 326, nombre: "Guía de traducción enana", tipo: "Fabricable" },
{ id: 328, nombre: "Suelo de madera", tipo: "Fabricable" },
{ id: 329, nombre: "Suelo de piedra", tipo: "Fabricable" },
{ id: 331, nombre: "Suelo desgastado", tipo: "Fabricable" },
{ id: 333, nombre: "Suelo de cristal", tipo: "Fabricable" },
{ id: 349, nombre: "Tónico energético", tipo: "Fabricable" },
{ id: 351, nombre: "Remedio muscular", tipo: "Fabricable" },
{ id: 395, nombre: "Café", tipo: "Fabricable" },
{ id: 401, nombre: "Piso de paja", tipo: "Fabricable" },
{ id: 403, nombre: "Merienda de campo", tipo: "Fabricable" },
{ id: 405, nombre: "Sendero de madera", tipo: "Fabricable" },
{ id: 407, nombre: "Camino de grava", tipo: "Fabricable" },
{ id: 409, nombre: "Camino de cristal", tipo: "Fabricable" },
{ id: 411, nombre: "Camino empedrado", tipo: "Fabricable" },
{ id: 415, nombre: "Sendero de piedras para cruzar", tipo: "Fabricable" },
{ id: 434, nombre: "Stardrop", tipo: "Fabricable" },
{ id: 461, nombre: "Maceta decorativa", tipo: "Fabricable" },
{ id: 463, nombre: "Bloque de tambor", tipo: "Fabricable" },
{ id: 464, nombre: "Bloque de flauta", tipo: "Fabricable" },
{ id: 599, nombre: "Aspersor", tipo: "Fabricable" },
{ id: 621, nombre: "Aspersor de calidad", tipo: "Fabricable" },
{ id: 645, nombre: "Aspersor de iridio", tipo: "Fabricable" },
{ id: 681, nombre: "Tótem de la lluvia", tipo: "Fabricable" },
{ id: 688, nombre: "Tótem de teletransporte: Granja", tipo: "Fabricable" },
{ id: 689, nombre: "Tótem de distorsión: Montaña", tipo: "Fabricable" },
{ id: 690, nombre: "Tótem de teletransporte: Playa", tipo: "Fabricable" },
{ id: 710, nombre: "Olla para cangrejos", tipo: "Fabricable" },
{ id: 746, nombre: "Calabaza de Halloween", tipo: "Fabricable" },
{ id: 840, nombre: "Suelo de tablones rústicos", tipo: "Fabricable" },
{ id: 841, nombre: "Suelo de pasarela de piedra", tipo: "Fabricable" },
{ id: 874, nombre: "Filete de insecto", tipo: "Fabricable" },
{ id: 877, nombre: "Monstruo almizcle", tipo: "Fabricable" },
{ id: 886, nombre: "Tótem de teletransporte: Isla", tipo: "Fabricable" },
{ id: 891, nombre: "Semilla de árbol de setas", tipo: "Fabricable" },
{ id: 912, nombre: "Tótem de Distorsión: Arena del tiempo", tipo: "Fabricable" },
{ id: 913, nombre: "Fuegos artificiales (rojos)", tipo: "Fabricable" },
{ id: 914, nombre: "Fuegos artificiales (morados)", tipo: "Fabricable" },
{ id: 915, nombre: "Fuegos artificiales (verdes)", tipo: "Fabricable" },
{ id: 815, nombre: "Alma galáctica", tipo: "Fabricable" },
{ id: 911, nombre: "Flauta de caballo", tipo: "Fabricable" },
{ id: 922, nombre: "Caja de suministros A", tipo: "Fabricable" },
{ id: 923, nombre: "Caja de suministros B", tipo: "Fabricable" },
{ id: 924, nombre: "Caja de suministros C", tipo: "Fabricable" },
{ id: 925, nombre: "Caja de limo", tipo: "Fabricable" },
{ id: 926, nombre: "Kit para barbacoa", tipo: "Fabricable" },
{ id: 927, nombre: "Hornillo de camping", tipo: "Fabricable" },
{ id: 929, nombre: "Cobertura", tipo: "Fabricable" },
{ id: "MossySeed", nombre: "Semilla musgosa", tipo: "Fabricable" },
{ id: "Kit de tienda de campaña", nombre: "Kit de tienda de campaña", tipo: "Fabricable" },
{ id: "MysticTreeSeed", nombre: "Semilla de árbol místico", tipo: "Fabricable" },
{ id: "TreasureTotem", nombre: "Tótem del tesoro", tipo: "Fabricable" },
{ id: "BlueGrassStarter", nombre: "Iniciador de Blue Grass", tipo: "Fabricable" },

    // Categoría de Cocina

{ id: 194, nombre: "Huevo frito", tipo: "Cocina" },
{ id: 195, nombre: "Tortilla", tipo: "Cocina" },
{ id: 196, nombre: "Ensalada", tipo: "Cocina" },
{ id: 197, nombre: "Coliflor con queso", tipo: "Cocina" },
{ id: 198, nombre: "Pescado al horno", tipo: "Cocina" },
{ id: 199, nombre: "Sopa de chirivía", tipo: "Cocina" },
{ id: 200, nombre: "Mezcla de verduras", tipo: "Cocina" },
{ id: 201, nombre: "Desayuno completo", tipo: "Cocina" },
{ id: 202, nombre: "Calamares fritos", tipo: "Cocina" },
{ id: 203, nombre: "Extraña cena", tipo: "Cocina" },
{ id: 204, nombre: "Almuerzo de la suerte", tipo: "Cocina" },
{ id: 205, nombre: "Champiñones fritos", tipo: "Cocina" },
{ id: 206, nombre: "Pizza", tipo: "Cocina" },
{ id: 207, nombre: "Olla caliente de frijoles", tipo: "Cocina" },
{ id: 208, nombre: "Ñames glaseados", tipo: "Cocina" },
{ id: 209, nombre: "Sorpresa de carpa", tipo: "Cocina" },
{ id: 210, nombre: "Hash browns", tipo: "Cocina" },
{ id: 211, nombre: "Panqueques", tipo: "Cocina" },
{ id: 212, nombre: "Cena de salmón", tipo: "Cocina" },
{ id: 213, nombre: "Taco de pescado", tipo: "Cocina" },
{ id: 214, nombre: "Lubina crujiente", tipo: "Cocina" },
{ id: 215, nombre: "Pepper Poppers", tipo: "Cocina" },
{ id: 216, nombre: "Pan", tipo: "Cocina" },
{ id: 218, nombre: "Sopa Tom Kha", tipo: "Cocina" },
{ id: 219, nombre: "Sopa de trucha", tipo: "Cocina" },
{ id: 220, nombre: "Pastel de chocolate", tipo: "Cocina" },
{ id: 221, nombre: "Pastel rosa", tipo: "Cocina" },
{ id: 222, nombre: "Pastel de ruibarbo", tipo: "Cocina" },
{ id: 223, nombre: "Galletas", tipo: "Cocina" },
{ id: 224, nombre: "Espaguetis", tipo: "Cocina" },
{ id: 225, nombre: "Anguila frita", tipo: "Cocina" },
{ id: 226, nombre: "Anguila picante", tipo: "Cocina" },
{ id: 227, nombre: "Sashimi", tipo: "Cocina" },
{ id: 228, nombre: "Maki Roll", tipo: "Cocina" },
{ id: 229, nombre: "Tortilla (Masa)", tipo: "Cocina" },
{ id: 230, nombre: "Plato rojo", tipo: "Cocina" },
{ id: 231, nombre: "Berenjena a la parmesana", tipo: "Cocina" },
{ id: 232, nombre: "Arroz con leche", tipo: "Cocina" },
{ id: 233, nombre: "Helado", tipo: "Cocina" },
{ id: 234, nombre: "Tarta de arándanos", tipo: "Cocina" },
{ id: 235, nombre: "La abundancia del otoño", tipo: "Cocina" },
{ id: 236, nombre: "Sopa de calabaza", tipo: "Cocina" },
{ id: 237, nombre: "Súper comida", tipo: "Cocina" },
{ id: 238, nombre: "Salsa de arándanos", tipo: "Cocina" },
{ id: 239, nombre: "Relleno", tipo: "Cocina" },
{ id: 240, nombre: "Almuerzo del granjero", tipo: "Cocina" },
{ id: 241, nombre: "Hamburguesa de supervivencia", tipo: "Cocina" },
{ id: 242, nombre: "Plato del mar", tipo: "Cocina" },
{ id: 243, nombre: "El regalo del minero", tipo: "Cocina" },
{ id: 244, nombre: "Roots Platter", tipo: "Cocina" },
{ id: 253, nombre: "Espresso triple", tipo: "Cocina" },
{ id: 604, nombre: "Pudín de espuma de mar", tipo: "Cocina" },
{ id: 605, nombre: "Caramelo de roca mágico", tipo: "Cocina" },
{ id: 456, nombre: "Sopa de algas", tipo: "Cocina" },
{ id: 457, nombre: "Caldo pálido", tipo: "Cocina" },
{ id: 606, nombre: "Pudín de ciruelas", tipo: "Cocina" },
{ id: 607, nombre: "Dip de alcachofa", tipo: "Cocina" },
{ id: 608, nombre: "Salteado", tipo: "Cocina" },
{ id: 609, nombre: "Avellanas tostadas", tipo: "Cocina" },
{ id: 610, nombre: "Pastel de calabaza", tipo: "Cocina" },
{ id: 611, nombre: "Ensalada de rábanos", tipo: "Cocina" },
{ id: 612, nombre: "Ensalada de fruta", tipo: "Cocina" },
{ id: 613, nombre: "Pastel de moras", tipo: "Cocina" },
{ id: 614, nombre: "Caramelos de arándano", tipo: "Cocina" },
{ id: 618, nombre: "Bruschetta", tipo: "Cocina" },
{ id: 639, nombre: "Estofado de col", tipo: "Cocina" },
{ id: 640, nombre: "Caldo de huevos de pescado", tipo: "Cocina" },
{ id: 641, nombre: "Magdalenas de semillas de amapola", tipo: "Cocina" },
{ id: 727, nombre: "Sopa de pescado", tipo: "Cocina" },
{ id: 728, nombre: "Sopa de pescado", tipo: "Cocina" }, // Variación
{ id: 729, nombre: "Carpaccio", tipo: "Cocina" },
{ id: 730, nombre: "Sopa de langosta", tipo: "Cocina" },
{ id: 731, nombre: "Barra de arce", tipo: "Cocina" },
{ id: 732, nombre: "Pasteles de cangrejo", tipo: "Cocina" },
{ id: 733, nombre: "Cóctel de camarones", tipo: "Cocina" },
{ id: 805, nombre: "Aceite de ajo", tipo: "Cocina" },
{ id: 807, nombre: "Elixir de la vida", tipo: "Cocina" },
{ id: 808, nombre: "Sopa de mango", tipo: "Cocina" },
{ id: 809, nombre: "Curry tropical", tipo: "Cocina" },
{ id: 810, nombre: "Helado de fruta de dragón", tipo: "Cocina" },
    
    // Categoría de Semillas

{ id: 273, nombre: "Brote de arroz", tipo: "Semilla" },
{ id: 299, nombre: "Semillas de amaranto", tipo: "Semilla" },
{ id: 301, nombre: "Iniciador de uva", tipo: "Semilla" },
{ id: 302, nombre: "Iniciador de lúpulo", tipo: "Semilla" },
{ id: 347, nombre: "Semilla rara", tipo: "Semilla" },
{ id: 425, nombre: "Semillas de hadas", tipo: "Semilla" },
{ id: 427, nombre: "Bulbo de tulipán", tipo: "Semilla" },
{ id: 429, nombre: "Semillas de jazz", tipo: "Semilla" },
{ id: 431, nombre: "Semillas de girasol", tipo: "Semilla" },
{ id: 433, nombre: "Grano de café", tipo: "Semilla" },
{ id: 453, nombre: "Semillas de amapola", tipo: "Semilla" },
{ id: 455, nombre: "Semillas de lentejuelas", tipo: "Semilla" },
{ id: 472, nombre: "Semillas de chirivía", tipo: "Semilla" },
{ id: 473, nombre: "Iniciador de frijoles", tipo: "Semilla" },
{ id: 474, nombre: "Semillas de coliflor", tipo: "Semilla" },
{ id: 475, nombre: "Semillas de papa", tipo: "Semilla" },
{ id: 476, nombre: "Semillas de ajo", tipo: "Semilla" },
{ id: 477, nombre: "Semillas de col rizada", tipo: "Semilla" },
{ id: 478, nombre: "Semillas de ruibarbo", tipo: "Semilla" },
{ id: 479, nombre: "Semillas de melón", tipo: "Semilla" },
{ id: 480, nombre: "Semillas de tomate", tipo: "Semilla" },
{ id: 481, nombre: "Semillas de arándano", tipo: "Semilla" },
{ id: 482, nombre: "Semillas de pimiento", tipo: "Semilla" },
{ id: 483, nombre: "Semillas de trigo", tipo: "Semilla" },
{ id: 484, nombre: "Semillas de rábano", tipo: "Semilla" },
{ id: 485, nombre: "Semillas de col lombarda", tipo: "Semilla" },
{ id: 486, nombre: "Semillas de carambola", tipo: "Semilla" },
{ id: 487, nombre: "Semillas de maíz", tipo: "Semilla" },
{ id: 488, nombre: "Semillas de berenjena", tipo: "Semilla" },
{ id: 489, nombre: "Semillas de alcachofa", tipo: "Semilla" },
{ id: 490, nombre: "Semillas de calabaza", tipo: "Semilla" },
{ id: 491, nombre: "Semillas de bok choy", tipo: "Semilla" },
{ id: 492, nombre: "Semillas de ñame", tipo: "Semilla" },
{ id: 493, nombre: "Semillas de arándano rojo", tipo: "Semilla" },
{ id: 494, nombre: "Semillas de remolacha", tipo: "Semilla" },
{ id: 495, nombre: "Semillas de primavera", tipo: "Semilla" },
{ id: 496, nombre: "Semillas de verano", tipo: "Semilla" },
{ id: 497, nombre: "Semillas de otoño", tipo: "Semilla" },
{ id: 498, nombre: "Semillas de invierno", tipo: "Semilla" },
{ id: 499, nombre: "Semillas antiguas", tipo: "Semilla" },
{ id: 745, nombre: "Semillas de fresa", tipo: "Semilla" },
{ id: 770, nombre: "Semillas mixtas", tipo: "Semilla" },
{ id: 802, nombre: "Semillas de cactus", tipo: "Semilla" },
{ id: 831, nombre: "Tubérculo de taro", tipo: "Semilla" },
{ id: 833, nombre: "Semillas de piña", tipo: "Semilla" },
{ id: 885, nombre: "Semillas de fibra", tipo: "Semilla" },
{ id: 890, nombre: "frijol qi", tipo: "Semilla" },
{ id: "Semillas de flores mixtas", nombre: "Semillas de flores mixtas", tipo: "Semilla" },
{ id: "Zanahoria", nombre: "Semillas de zanahoria", tipo: "Semilla" },
{ id: "Calabaza de verano", nombre: "Semillas de calabaza de verano", tipo: "Semilla" },
{ id: "Brócoli", nombre: "Semillas de brócoli", tipo: "Semilla" },
{ id: "Melón en polvo", nombre: "Semillas de melón en polvo", tipo: "Semilla" },
    
    // Categoría de Pescados

    { id: 128, nombre: "Pez globo", tipo: "Pescado" },
    { id: 129, nombre: "Anchoa", tipo: "Pescado" },
    { id: 130, nombre: "Atún", tipo: "Pescado" },
    { id: 131, nombre: "Sardina", tipo: "Pescado" },
    { id: 132, nombre: "Japuta", tipo: "Pescado" },
    { id: 136, nombre: "Lubina de boca grande", tipo: "Pescado" },
    { id: 137, nombre: "Lubina de boca pequeña", tipo: "Pescado" },
    { id: 138, nombre: "Trucha arcoíris", tipo: "Pescado" },
    { id: 139, nombre: "Salmón", tipo: "Pescado" },
    { id: 140, nombre: "Lucioperca", tipo: "Pescado" },
    { id: 141, nombre: "Perca", tipo: "Pescado" },
    { id: 142, nombre: "Carpa", tipo: "Pescado" },
    { id: 143, nombre: "Bagre", tipo: "Pescado" },
    { id: 144, nombre: "Lucio", tipo: "Pescado" },
    { id: 145, nombre: "Pez sol", tipo: "Pescado" },
    { id: 146, nombre: "Salmonete", tipo: "Pescado" },
    { id: 147, nombre: "Arenque", tipo: "Pescado" },
    { id: 148, nombre: "Anguila", tipo: "Pescado" },
    { id: 149, nombre: "Pulpo", tipo: "Pescado" },
    { id: 150, nombre: "Pargo", tipo: "Pescado" },
    { id: 151, nombre: "Calamar", tipo: "Pescado" },
    { id: 152, nombre: "Alga", tipo: "Pescado" },
    { id: 153, nombre: "Algas verdes", tipo: "Pescado" },
    { id: 154, nombre: "Pepino de mar", tipo: "Pescado" },
    { id: 155, nombre: "Superpepino", tipo: "Pescado" },
    { id: 156, nombre: "Pez fantasma", tipo: "Pescado" },
    { id: 157, nombre: "Algas blancas", tipo: "Pescado" },
    { id: 158, nombre: "Pez piedra", tipo: "Pescado" },
    { id: 159, nombre: "Pez carmesí", tipo: "Pescado" },
    { id: 160, nombre: "Pescador de caña", tipo: "Pescado" },
    { id: 161, nombre: "Pip de hielo", tipo: "Pescado" },
    { id: 162, nombre: "Anguila de lava", tipo: "Pescado" },
    { id: 163, nombre: "Leyenda", tipo: "Pescado" },
    { id: 164, nombre: "Pez de arena", tipo: "Pescado" },
    { id: 165, nombre: "Carpa escorpión", tipo: "Pescado" },
    { id: 167, nombre: "Joja Cola", tipo: "Pescado" },
    { id: 168, nombre: "Basura", tipo: "Pescado" },
    { id: 169, nombre: "Madera a la deriva", tipo: "Pescado" },
    { id: 170, nombre: "Cristales rotos", tipo: "Pescado" },
    { id: 171, nombre: "CD roto", tipo: "Pescado" },
    { id: 172, nombre: "Periódico empapado", tipo: "Pescado" },
    { id: 267, nombre: "Platija", tipo: "Pescado" },
    { id: 269, nombre: "Carpa de medianoche", tipo: "Pescado" },
    { id: 372, nombre: "Almeja", tipo: "Pescado" },
    { id: 442, nombre: "Carpa mutante", tipo: "Pescado" },
    { id: 444, nombre: "Esturión", tipo: "Pescado" },
    { id: 446, nombre: "Trucha tigre", tipo: "Pescado" },
    { id: 682, nombre: "Brótola", tipo: "Pescado" },
    { id: 698, nombre: "Tilapia", tipo: "Pescado" },
    { id: 699, nombre: "Cacho", tipo: "Pescado" },
    { id: 700, nombre: "Dorado", tipo: "Pescado" },
    { id: 701, nombre: "Albúmina blanco", tipo: "Pescado" },
    { id: 702, nombre: "Sábalo", tipo: "Pescado" },
    { id: 704, nombre: "Besugo", tipo: "Pescado" },
    { id: 705, nombre: "Halibut", tipo: "Pescado" },
    { id: 706, nombre: "Langosta", tipo: "Pescado" },
    { id: 707, nombre: "Cangrejo de río", tipo: "Pescado" },
    { id: 708, nombre: "Cangrejo", tipo: "Pescado" },
    { id: 715, nombre: "Berberecho", tipo: "Pescado" },
    { id: 716, nombre: "Mejillón", tipo: "Pescado" },
    { id: 717, nombre: "Camarón", tipo: "Pescado" },
    { id: 718, nombre: "Caracol", tipo: "Pescado" },
    { id: 719, nombre: "Bígaro", tipo: "Pescado" },
    { id: 720, nombre: "Ostra", tipo: "Pescado" },
    { id: 734, nombre: "Woodskip", tipo: "Pescado" },
    { id: 775, nombre: "Pez glaciar", tipo: "Pescado" },
    { id: 795, nombre: "Salmón del vacío", tipo: "Pescado" },
    { id: 796, nombre: "Baba-pez", tipo: "Pescado" },
    { id: 798, nombre: "Calamar de medianoche", tipo: "Pescado" },
    { id: 799, nombre: "Pez fantasma (Mar)", tipo: "Pescado" },
    { id: 800, nombre: "Pez borrón", tipo: "Pescado" },
    { id: 830, nombre: "Raya", tipo: "Pescado" },
    { id: 831, nombre: "Pez león", tipo: "Pescado" },
    { id: 832, nombre: "Disco azul", tipo: "Pescado" },
    { id: 898, nombre: "Hijo del pez carmesí", tipo: "Pescado" },
    { id: 899, nombre: "Sra. Angler", tipo: "Pescado" },
    { id: 900, nombre: "Leyenda II", tipo: "Pescado" },
    { id: 901, nombre: "Carpa radiactiva", tipo: "Pescado" },
    { id: 902, nombre: "Pez glaciar Jr.", tipo: "Pescado" },
    { id: "SeaJelly", nombre: "Medusa marina", tipo: "Pescado" },
    { id: "RiverJelly", nombre: "Medusa de río", tipo: "Pescado" },
    { id: "CaveJelly", nombre: "Medusa de cueva", tipo: "Pescado" },
    { id: "Goby", nombre: "Gobio", tipo: "Pescado" },

    // CATEGORÍA de MINERALES
        
    { id: 60, nombre: "Esmeralda", tipo: "Mineral" },
    { id: 62, nombre: "Aguamarina", tipo: "Mineral" },
    { id: 64, nombre: "Rubí", tipo: "Mineral" },
    { id: 66, nombre: "Amatista", tipo: "Mineral" },
    { id: 68, nombre: "Topacio", tipo: "Mineral" },
    { id: 70, nombre: "Jade", tipo: "Mineral" },
    { id: 72, nombre: "Diamante", tipo: "Mineral" },
    { id: 74, nombre: "Fragmento prismático", tipo: "Mineral" },
    { id: 80, nombre: "Cuarzo", tipo: "Mineral" },
    { id: 82, nombre: "Cuarzo de fuego", tipo: "Mineral" },
    { id: 84, nombre: "Lágrima congelada", tipo: "Mineral" },
    { id: 86, nombre: "Cristal de la Tierra", tipo: "Mineral" },
    { id: 538, nombre: "Alamita", tipo: "Mineral" },
    { id: 539, nombre: "Bixita", tipo: "Mineral" },
    { id: 540, nombre: "Barita", tipo: "Mineral" },
    { id: 541, nombre: "Aerinita", tipo: "Mineral" },
    { id: 542, nombre: "Calcita", tipo: "Mineral" },
    { id: 543, nombre: "Dolomita", tipo: "Mineral" },
    { id: 544, nombre: "Esperite", tipo: "Mineral" },
    { id: 545, nombre: "Fluorapatita", tipo: "Mineral" },
    { id: 546, nombre: "Geminita", tipo: "Mineral" },
    { id: 547, nombre: "Helvita", tipo: "Mineral" },
    { id: 548, nombre: "Jamborite", tipo: "Mineral" },
    { id: 549, nombre: "Jagoíta", tipo: "Mineral" },
    { id: 550, nombre: "Cianita", tipo: "Mineral" },
    { id: 551, nombre: "Lunarita", tipo: "Mineral" },
    { id: 552, nombre: "Malaquita", tipo: "Mineral" },
    { id: 553, nombre: "Neptuno", tipo: "Mineral" },
    { id: 554, nombre: "Piedra de limón", tipo: "Mineral" },
    { id: 555, nombre: "Nekoite", tipo: "Mineral" },
    { id: 556, nombre: "Oropimente", tipo: "Mineral" },
    { id: 557, nombre: "Limo petrificado", tipo: "Mineral" },
    { id: 558, nombre: "Huevo de trueno", tipo: "Mineral" },
    { id: 559, nombre: "Pirita", tipo: "Mineral" },
    { id: 560, nombre: "Piedra del océano", tipo: "Mineral" },
    { id: 561, nombre: "Cristal fantasma", tipo: "Mineral" },
    { id: 562, nombre: "Ojo de tigre", tipo: "Mineral" },
    { id: 563, nombre: "Jaspe", tipo: "Mineral" },
    { id: 564, nombre: "Ópalo", tipo: "Mineral" },
    { id: 565, nombre: "Ópalo de fuego", tipo: "Mineral" },
    { id: 566, nombre: "Celestine", tipo: "Mineral" },
    { id: 567, nombre: "Mármol", tipo: "Mineral" },
    { id: 568, nombre: "Arenisca", tipo: "Mineral" },
    { id: 569, nombre: "Granito", tipo: "Mineral" },
    { id: 570, nombre: "Basalto", tipo: "Mineral" },
    { id: 571, nombre: "Caliza", tipo: "Mineral" },
    { id: 572, nombre: "Esteatita", tipo: "Mineral" },
    { id: 573, nombre: "Hematites", tipo: "Mineral" },
    { id: 574, nombre: "Piedra arcillosa", tipo: "Mineral" },
    { id: 575, nombre: "Obsidiana", tipo: "Mineral" },
    { id: 576, nombre: "Pizarra", tipo: "Mineral" },
    { id: 577, nombre: "Piedra de hadas", tipo: "Mineral" },
    { id: 578, nombre: "Fragmentos estelares", tipo: "Mineral" },

    // Categoría de Artefacto

    { id: 96, nombre: "Pergamino Enano I", tipo: "Artefacto" },
    { id: 97, nombre: "Pergamino del Enano II", tipo: "Artefacto" },
    { id: 98, nombre: "Pergamino Enano III", tipo: "Artefacto" },
    { id: 99, nombre: "Pergamino Enano IV", tipo: "Artefacto" },
    { id: 100, nombre: "Ánfora astillada", tipo: "Artefacto" },
    { id: 101, nombre: "Punta de flecha", tipo: "Artefacto" },
    { id: 103, nombre: "Muñeca antigua", tipo: "Artefacto" },
    { id: 104, nombre: "Joyería élfica", tipo: "Artefacto" },
    { id: 105, nombre: "Palito para masticar", tipo: "Artefacto" },
    { id: 106, nombre: "Ventilador ornamental", tipo: "Artefacto" },
    { id: 107, nombre: "Huevo de dinosaurio", tipo: "Artefacto" },
    { id: 108, nombre: "Disco raro", tipo: "Artefacto" },
    { id: 109, nombre: "Espada antigua", tipo: "Artefacto" },
    { id: 110, nombre: "Cuchara oxidada", tipo: "Artefacto" },
    { id: 111, nombre: "Espuela oxidada", tipo: "Artefacto" },
    { id: 112, nombre: "Engranaje oxidado", tipo: "Artefacto" },
    { id: 113, nombre: "Estatua de pollo", tipo: "Artefacto" },
    { id: 114, nombre: "Semilla antigua", tipo: "Artefacto" },
    { id: 115, nombre: "Herramienta prehistórica", tipo: "Artefacto" },
    { id: 116, nombre: "Estrella de mar seca", tipo: "Artefacto" },
    { id: 117, nombre: "Ancla", tipo: "Artefacto" },
    { id: 118, nombre: "Fragmentos de vidrio", tipo: "Artefacto" },
    { id: 119, nombre: "Flauta de hueso", tipo: "Artefacto" },
    { id: 120, nombre: "Hacha de mano prehistórica", tipo: "Artefacto" },
    { id: 121, nombre: "Yelmo enano", tipo: "Artefacto" },
    { id: 122, nombre: "Gadget enano", tipo: "Artefacto" },
    { id: 123, nombre: "Tambor antiguo", tipo: "Artefacto" },
    { id: 124, nombre: "Máscara Dorada", tipo: "Artefacto" },
    { id: 125, nombre: "Reliquia dorada", tipo: "Artefacto" },
    { id: 126, nombre: "Muñeca extraña (Verde)", tipo: "Artefacto" },
    { id: 127, nombre: "Muñeca extraña (Rosa)", tipo: "Artefacto" },
    { id: 579, nombre: "Escápula prehistórica", tipo: "Artefacto" },
    { id: 580, nombre: "Tibia prehistórica", tipo: "Artefacto" },
    { id: 581, nombre: "Cráneo prehistórico", tipo: "Artefacto" },
    { id: 582, nombre: "Mano esquelética", tipo: "Artefacto" },
    { id: 583, nombre: "Costilla prehistórica", tipo: "Artefacto" },
    { id: 584, nombre: "Vértebras prehistóricas", tipo: "Artefacto" },
    { id: 585, nombre: "Cola esquelética", tipo: "Artefacto" },
    { id: 586, nombre: "Fósil de nautilo", tipo: "Artefacto" },
    { id: 587, nombre: "Fósil de anfibio", tipo: "Artefacto" },
    { id: 588, nombre: "Fósil de palma", tipo: "Artefacto" },
    { id: 589, nombre: "Trilobite", tipo: "Artefacto" },

        // Categoría de Anillos

{ id: 516, nombre: "Anillo pequeño que brilla en la oscuridad", tipo: "Anillo" },
{ id: 517, nombre: "Anillo luminoso", tipo: "Anillo" },
{ id: 518, nombre: "Anillo magnético pequeño", tipo: "Anillo" },
{ id: 519, nombre: "Anillo magnético", tipo: "Anillo" },
{ id: 520, nombre: "Anillo encantador de limo", tipo: "Anillo" },
{ id: 521, nombre: "Anillo de guerrero", tipo: "Anillo" },
{ id: 522, nombre: "Anillo de vampiro", tipo: "Anillo" },
{ id: 523, nombre: "Anillo salvaje", tipo: "Anillo" },
{ id: 524, nombre: "Anillo de Yoba", tipo: "Anillo" },
{ id: 525, nombre: "Anillo resistente", tipo: "Anillo" },
{ id: 526, nombre: "Anillo de ladrones", tipo: "Anillo" },
{ id: 527, nombre: "Banda de iridio", tipo: "Anillo" },
{ id: 528, nombre: "Anillo de la máquina de discos", tipo: "Anillo" },
{ id: 529, nombre: "Anillo de amatista", tipo: "Anillo" },
{ id: 530, nombre: "Anillo de topacio", tipo: "Anillo" },
{ id: 531, nombre: "Anillo de aguamarina", tipo: "Anillo" },
{ id: 532, nombre: "Anillo de jade", tipo: "Anillo" },
{ id: 533, nombre: "Anillo de esmeralda", tipo: "Anillo" },
{ id: 534, nombre: "Anillo de rubí", tipo: "Anillo" },
{ id: 801, nombre: "Anillo de boda", tipo: "Anillo" },
{ id: 810, nombre: "Anillo de concha de cangrejo", tipo: "Anillo" },
{ id: 811, nombre: "Anillo de napalm", tipo: "Anillo" },
{ id: 839, nombre: "Anillo de espinas", tipo: "Anillo" },
{ id: 859, nombre: "Anillo de la suerte", tipo: "Anillo" },
{ id: 860, nombre: "Anillo de Java caliente", tipo: "Anillo" },
{ id: 861, nombre: "Anillo de protección", tipo: "Anillo" },
{ id: 862, nombre: "Anillo Sacador de Almas", tipo: "Anillo" },
{ id: 863, nombre: "Anillo del Fénix", tipo: "Anillo" },
{ id: 880, nombre: "Anillo combinado", tipo: "Anillo" },
{ id: 887, nombre: "Pulsera de inmunidad", tipo: "Anillo" },
{ id: 888, nombre: "Anillo de piedra luminosa", tipo: "Anillo" },

        // Categoría de Misiones

    { id: 71, nombre: "Pantalones cortos Lucky Purple recortados", tipo: "Mision" },
    { id: 191, nombre: "Collar ornamentado", tipo: "Mision" },
    { id: 742, nombre: "La pulsera perdida de Haley", tipo: "Mision" },
    { id: 788, nombre: "Hacha perdida", tipo: "Mision" },
    { id: 789, nombre: "Pantalones cortos morados de la suerte", tipo: "Mision" },
    { id: 790, nombre: "Cesta de bayas", tipo: "Mision" },
    { id: 791, nombre: "Coco dorado", tipo: "Mision" },
    { id: 864, nombre: "Recuerdo de guerra", tipo: "Mision" },
    { id: 865, nombre: "Sal de tomate gourmet", tipo: "Mision" },
    { id: 866, nombre: "Rosa de Stardew Valley", tipo: "Mision" },
    { id: 867, nombre: "Control remoto avanzado para TV", tipo: "Mision" },
    { id: 868, nombre: "Fragmento Ártico", tipo: "Mision" },
    { id: 869, nombre: "Gusano retorciéndose", tipo: "Mision" },
    { id: 870, nombre: "Medallón de pirata", tipo: "Mision" },
    { id: 875, nombre: "Ectoplasma", tipo: "Mision" },
    { id: 876, nombre: "Gelatina prismática", tipo: "Mision" },
    { id: 897, nombre: "Lista de productos desaparecidos de Pierre", tipo: "Mision" },
    { id: "GoldenBobber", nombre: "Bobber dorado", tipo: "Mision" },
    { id: "WarMemento", nombre: "Recuerdo de guerra (Alternativo)", tipo: "Mision" },

        // Categoría de Misc

{ id: 79, nombre: "Nota secreta", tipo: "Misc" },
{ id: 102, nombre: "Libro perdido", tipo: "Misc" },
{ id: 449, nombre: "Base de piedra", tipo: "Misc" },
{ id: 590, nombre: "Lugar de artefactos", tipo: "Misc" },
{ id: 842, nombre: "Fragmento de diario", tipo: "Misc" },

{ id: "SeedSpot", nombre: "Lugar de artefactos (Semilla)", tipo: "Misc" },
{ id: "Libro morado", nombre: "Libro de las estrellas", tipo: "Misc" },
{ id: "SkillBook_0", nombre: "Almanaque de Stardew Valley", tipo: "Misc" },
{ id: "Libro de habilidades_2", nombre: "Semanario del Leñador", tipo: "Misc" },
{ id: "Libro de habilidades_1", nombre: "Cebo y flotador", tipo: "Misc" },
{ id: "Libro de habilidades_3", nombre: "Minería Mensual", tipo: "Misc" },
{ id: "Libro de habilidades_4", nombre: "Trimestre de combate", tipo: "Misc" },
{ id: "Basura de libros", nombre: "El buffet del callejón", tipo: "Misc" },
{ id: "Libro_de_Crabbing", nombre: "El arte de la pesca de cangrejos", tipo: "Misc" },
{ id: "Bombas de libros", nombre: "Manual de seguridad enano", tipo: "Misc" },
{ id: "Libro_Roe", nombre: "Joyas del mar", tipo: "Misc" },
{ id: "Libro_SemillasSilvestres", nombre: "Revista del mapache", tipo: "Misc" },
{ id: "Libro_Talla de madera", nombre: "El secreto de Woody", tipo: "Misc" },
{ id: "Defensa de libros", nombre: "Jack sea ágil, Jack sea grueso", tipo: "Misc" },
{ id: "Amistad_con_libros", nombre: "Introducción a la amistad", tipo: "Misc" },
{ id: "Libro_Vacio", nombre: "Compendio de monstruos", tipo: "Misc" },
{ id: "Velocidad de lectura", nombre: "El camino del viento, parte 1", tipo: "Misc" },
{ id: "Libro_Marlon", nombre: "Cartografía de sistemas de cuevas", tipo: "Misc" },
{ id: "Catálogo de precios de libros", nombre: "Catálogo de precios", tipo: "Misc" },
{ id: "Book_QueenOfSauce", nombre: "Libro de cocina de la reina de las salsas", tipo: "Misc" },
{ id: "Diamantes de libros", nombre: "El cazador de diamantes", tipo: "Misc" },
{ id: "Libro_Misterio", nombre: "Libro de misterios", tipo: "Misc" },
{ id: "Catálogo_de_Animales_de_Libros", nombre: "Catálogo de animales", tipo: "Misc" },
{ id: "Book_Speed2", nombre: "El camino del viento, parte 2", tipo: "Misc" },
{ id: "GoldenAnimalCracker", nombre: "Galleta de animales dorada", tipo: "Misc" },
{ id: "Libro_Artefacto", nombre: "Guía de tasación de tesoros", tipo: "Misc" },
{ id: "Libro_Caballo", nombre: "El caballo: El libro", tipo: "Misc" },
{ id: "Libro_Hierba", nombre: "El viejo Patas de Trampa", tipo: "Misc" },
];

const listaVisual = document.getElementById("listaVisual");
const inputFiltro = document.getElementById("filtro");

function cargarItems(items) {
    if (!listaVisual) return;
    listaVisual.innerHTML = ""; 

    items.forEach(item => {
        const li = document.createElement("li");
        li.innerHTML = `
            <span class="item-id">[${item.id}]</span>
            <span class="item-nombre"> - ${item.nombre}</span>
            <button class="btn-copy-corner" onclick="copiarID('${item.id}')" title="Copiar ID">
                <img src="https://cdn-icons-png.flaticon.com/512/1621/1621635.png" alt="copy">
            </button>
            <span class="tag-tipo">${item.tipo}</span>
        `;
        listaVisual.appendChild(li);
    });
}

function copiarID(id) {
    const textoACopiar = "[" + id + "]";
    navigator.clipboard.writeText(textoACopiar).then(() => {
        console.log("Copiado: " + textoACopiar);
    }).catch(err => {
        console.error("Error: ", err);
    });
}

function filtrar() {
    const busqueda = inputFiltro.value.toLowerCase();
    const filtrados = dbItems.filter(item => 
        item.nombre.toLowerCase().includes(busqueda) || 
        item.id.toString().toLowerCase().includes(busqueda)
    );
    cargarItems(filtrados);
}

function filtrarPorClase(categoriaSeleccionada) {
    if (categoriaSeleccionada === 'Todos') {
        cargarItems(dbItems);
    } else {
        const filtrados = dbItems.filter(item => item.tipo === categoriaSeleccionada);
        cargarItems(filtrados);
    }
    inputFiltro.value = ""; 
}

function toggleDarkMode() {
    document.body.classList.toggle("dark-theme");
}

window.onload = () => {
    if (typeof dbItems !== 'undefined') {
        cargarItems(dbItems);
    } else {
        console.error("dbItems no definido.");
    }
};
