// BASE DE DATOS
const dbItems = [
    //Categoría de Muebles
    { id: "(F)0", nombre: "Silla de roble", tipo: "Mueble" },
    { id: "(F)3", nombre: "Silla de nogal", tipo: "Mueble" },
    { id: "(F)6", nombre: "Silla de abedul", tipo: "Mueble" },
    { id: "(F)9", nombre: "Silla de caoba", tipo: "Mueble" },
    { id: "(F)12", nombre: "Silla de cafetería roja", tipo: "Mueble" },
    { id: "(F)15", nombre: "Silla de cafetería azul", tipo: "Mueble" },
    { id: "(F)18", nombre: "Silla de campo", tipo: "Mueble" },
    { id: "(F)21", nombre: "Silla de desayuno", tipo: "Mueble" },
    { id: "(F)24", nombre: "Silla de oficina rosa", tipo: "Mueble" },
    { id: "(F)27", nombre: "Silla de oficina morada", tipo: "Mueble" },
    { id: "(F)30", nombre: "Taburete de oficina verde", tipo: "Mueble" },
    { id: "(F)33", nombre: "Taburete de oficina naranja", tipo: "Mueble" },
    { id: "(F)64", nombre: "Trono oscuro", tipo: "Mueble" },
    { id: "(F)67", nombre: "Silla de comedor", tipo: "Mueble" },
    { id: "(F)73", nombre: "Asiento de felpa verde", tipo: "Mueble" },
    { id: "(F)76", nombre: "Asiento de felpa rosa", tipo: "Mueble" },
    { id: "(F)79", nombre: "Silla de invierno", tipo: "Mueble" },
    { id: "(F)82", nombre: "Silla moderna", tipo: "Mueble" },
    { id: "(F)85", nombre: "Silla mona", tipo: "Mueble" },
    { id: "(F)88", nombre: "Asiento de tocón", tipo: "Mueble" },
    { id: "(F)91", nombre: "Silla de metal", tipo: "Mueble" },
    { id: "(F)94", nombre: "Taburete verde", tipo: "Mueble" },
    { id: "(F)97", nombre: "Taburete azul", tipo: "Mueble" },
    { id: "(F)108", nombre: "Silla de rey", tipo: "Mueble" },
    { id: "(F)111", nombre: "Silla de cristal", tipo: "Mueble" },
    { id: "(F)114", nombre: "Silla tropical", tipo: "Mueble" },
    { id: "(F)115", nombre: "Banco de roble", tipo: "Mueble" },
    { id: "(F)117", nombre: "Banco de nogal", tipo: "Mueble" },
    { id: "(F)119", nombre: "Banco de abedul", tipo: "Mueble" },
    { id: "(F)121", nombre: "Banco de caoba", tipo: "Mueble" },
    { id: "(F)123", nombre: "Banco moderno", tipo: "Mueble" },
    { id: "(F)448", nombre: "Sillón azul", tipo: "Mueble" },
    { id: "(F)451", nombre: "Sillón rojo", tipo: "Mueble" },
    { id: "(F)454", nombre: "Sillón verde", tipo: "Mueble" },
    { id: "(F)457", nombre: "Sillón amarillo", tipo: "Mueble" },
    { id: "(F)460", nombre: "Sillón marrón", tipo: "Mueble" },
    { id: "(F)1118", nombre: "Sofá azul", tipo: "Mueble" },
    { id: "(F)1121", nombre: "Sofá rojo", tipo: "Mueble" },
    { id: "(F)1124", nombre: "Sofá verde", tipo: "Mueble" },
    { id: "(F)1127", nombre: "Sofá amarillo", tipo: "Mueble" },
    { id: "(F)1130", nombre: "Sofá marrón", tipo: "Mueble" },
    { id: "(F)1133", nombre: "Sofá oscuro", tipo: "Mueble" },
    { id: "(F)1136", nombre: "Sofá de mago", tipo: "Mueble" },
    { id: "(F)1139", nombre: "Sofá de madera", tipo: "Mueble" },
    { id: "(F)704", nombre: "Cómoda de roble", tipo: "Mueble" },
    { id: "(F)709", nombre: "Cómoda de nogal", tipo: "Mueble" },
    { id: "(F)714", nombre: "Cómoda de abedul", tipo: "Mueble" },
    { id: "(F)719", nombre: "Cómoda de caoba", tipo: "Mueble" },
    { id: "(F)724", nombre: "Mesa de café", tipo: "Mueble" },
    { id: "(F)727", nombre: "Losa de piedra", tipo: "Mueble" },
    { id: "(F)800", nombre: "Mesa de comedor de invierno", tipo: "Mueble" },
    { id: "(F)807", nombre: "Mesa de comedor festiva", tipo: "Mueble" },
    { id: "(F)814", nombre: "Mesa de comedor de caoba", tipo: "Mueble" },
    { id: "(F)821", nombre: "Mesa de comedor moderna", tipo: "Mueble" },
    { id: "(F)1120", nombre: "Mesa de roble", tipo: "Mueble" },
    { id: "(F)1123", nombre: "Mesa de nogal", tipo: "Mueble" },
    { id: "(F)1126", nombre: "Mesa de abedul", tipo: "Mueble" },
    { id: "(F)1129", nombre: "Mesa de caoba", tipo: "Mueble" },
    { id: "(F)1132", nombre: "Mesa de sol", tipo: "Mueble" },
    { id: "(F)1135", nombre: "Mesa de luna", tipo: "Mueble" },
    { id: "(F)1138", nombre: "Mesa moderna", tipo: "Mueble" },
    { id: "(F)1141", nombre: "Mesa de taberna", tipo: "Mueble" },
    { id: "(F)1144", nombre: "Mesa de lujo", tipo: "Mueble" },
    { id: "(F)1147", nombre: "Mesa divisoria", tipo: "Mueble" },
    { id: "(F)1150", nombre: "Mesa neolítica", tipo: "Mueble" },
    { id: "(F)1153", nombre: "Mesa oscura", tipo: "Mueble" },
    { id: "(F)1216", nombre: "Mesa de té de roble", tipo: "Mueble" },
    { id: "(F)1218", nombre: "Mesa de té de nogal", tipo: "Mueble" },
    { id: "(F)1220", nombre: "Mesa de té de abedul", tipo: "Mueble" },
    { id: "(F)1222", nombre: "Mesa de té de caoba", tipo: "Mueble" },
    { id: "(F)1224", nombre: "Mesa de té moderna", tipo: "Mueble" },
    { id: "(F)1226", nombre: "Catálogo de muebles", tipo: "Mueble" },
    { id: "(F)1229", nombre: "Alfombra oceánica", tipo: "Mueble" },
    { id: "(F)1280", nombre: "Vitrina de porcelana", tipo: "Mueble" },
    { id: "(F)1283", nombre: "Estantería de artista", tipo: "Mueble" },
    { id: "(F)1285", nombre: "Estantería de lujo", tipo: "Mueble" },
    { id: "(F)1287", nombre: "Estantería moderna", tipo: "Mueble" },
    { id: "(F)1289", nombre: "Estantería oscura", tipo: "Mueble" },
    { id: "(F)1291", nombre: "Pilar de cerámica", tipo: "Mueble" },
    { id: "(F)1293", nombre: "Pilar de oro", tipo: "Mueble" },
    { id: "(F)1295", nombre: "Tubería industrial", tipo: "Mueble" },
    { id: "(F)1296", nombre: "Palmera de interior", tipo: "Mueble" },
    { id: "(F)1297", nombre: "Tótem", tipo: "Mueble" },
    { id: "(F)1298", nombre: "Pino cuidado", tipo: "Mueble" },
    { id: "(F)1299", nombre: "Árbol topiario", tipo: "Mueble" },
    { id: "(F)1300", nombre: "Geoda en soporte", tipo: "Mueble" },
    { id: "(F)1301", nombre: "Jarrón de obsidiana", tipo: "Mueble" },
    { id: "(F)1302", nombre: "Piedra cantante", tipo: "Mueble" },
    { id: "(F)1303", nombre: "Esqueleto de perezoso (izq.)", tipo: "Mueble" },
    { id: "(F)1304", nombre: "Esqueleto de perezoso (centro)", tipo: "Mueble" },
    { id: "(F)1305", nombre: "Esqueleto de perezoso (der.)", tipo: "Mueble" },
    { id: "(F)1306", nombre: "Esqueleto", tipo: "Mueble" },
    { id: "(F)1307", nombre: "Estatua de pollo", tipo: "Mueble" },
    { id: "(F)1308", nombre: "Escultura de Leah", tipo: "Mueble" },
    { id: "(F)1309", nombre: "Girasoles secos", tipo: "Mueble" },
    { id: "(F)1310", nombre: "Catálogo", tipo: "Mueble" },
    { id: "(F)1311", nombre: "Radiocasete de Sam", tipo: "Mueble" },
    { id: "(F)1362", nombre: "Planta pequeña", tipo: "Mueble" },
    { id: "(F)1363", nombre: "Planta de mesa", tipo: "Mueble" },
    { id: "(F)1364", nombre: "Cuenco decorativo", tipo: "Mueble" },
    { id: "(F)1365", nombre: "Oso de peluche", tipo: "Mueble" },
    { id: "(F)1366", nombre: "Globo terráqueo", tipo: "Mueble" },
    { id: "(F)1367", nombre: "Barco de modelismo", tipo: "Mueble" },
    { id: "(F)1368", nombre: "Cristal pequeño", tipo: "Mueble" },
    { id: "(F)1369", nombre: "Farol decorativo", tipo: "Mueble" },
    { id: "(F)1371", nombre: "Estatua de Wumbus", tipo: "Mueble" },
    { id: "(F)1372", nombre: "Estatua de Bobo", tipo: "Mueble" },
    { id: "(F)1373", nombre: "Estatua de serpiente púrpura", tipo: "Mueble" },
    { id: "(F)1374", nombre: "Retrato de Jade", tipo: "Mueble" },
    { id: "(F)1375", nombre: "Cuadro de paisaje", tipo: "Mueble" },
    { id: "(F)1377", nombre: "Calavera de cristal", tipo: "Mueble" },
    { id: "(F)1378", nombre: "Estatua de la perfección", tipo: "Mueble" },
    { id: "(F)1379", nombre: "Estatua de la verdadera perfección", tipo: "Mueble" },
    { id: "(F)1380", nombre: "Cuadro 'Noche Estrellada'", tipo: "Mueble" },
    { id: "(F)1381", nombre: "Cuadro de volcán", tipo: "Mueble" },
    { id: "(F)1382", nombre: "Cuadro de desierto", tipo: "Mueble" },
    { id: "(F)1383", nombre: "Cuadro de pradera", tipo: "Mueble" },
    { id: "(F)1384", nombre: "Cuadro de océano", tipo: "Mueble" },
    { id: "(F)1390", nombre: "Póster de película", tipo: "Mueble" },
    { id: "(F)1391", nombre: "Póster de película (Terror)", tipo: "Mueble" },
    { id: "(F)1392", nombre: "Póster de película (Aventura)", tipo: "Mueble" },
    { id: "(F)1393", nombre: "Estatua de gato de la suerte", tipo: "Mueble" },
    { id: "(F)1460", nombre: "Bandera de pirata", tipo: "Mueble" },
    { id: "(F)1461", nombre: "Mapa del tesoro", tipo: "Mueble" },
    { id: "(F)1462", nombre: "Timón de barco", tipo: "Mueble" },
    { id: "(F)1466", nombre: "Aplique de pared", tipo: "Mueble" },
    { id: "(F)1468", nombre: "Antorcha de pared", tipo: "Mueble" },
    { id: "(F)1440", nombre: "Planta de interior 1", tipo: "Mueble" },
    { id: "(F)1441", nombre: "Planta de interior 2", tipo: "Mueble" },
    { id: "(F)1442", nombre: "Planta de interior 3", tipo: "Mueble" },
    { id: "(F)1443", nombre: "Planta de interior 4", tipo: "Mueble" },
    { id: "(F)1444", nombre: "Planta de interior 5", tipo: "Mueble" },
    { id: "(F)1445", nombre: "Planta de interior 6", tipo: "Mueble" },
    { id: "(F)1446", nombre: "Planta de interior 7", tipo: "Mueble" },
    { id: "(F)1447", nombre: "Planta de interior 8", tipo: "Mueble" },
    { id: "(F)1448", nombre: "Palmera seca", tipo: "Mueble" },
    { id: "(F)1449", nombre: "Planta colgante", tipo: "Mueble" },
    { id: "(F)1450", nombre: "Cactus de interior", tipo: "Mueble" },
    { id: "(F)1451", nombre: "Árbol de interior", tipo: "Mueble" },
    { id: "(F)1470", nombre: "Alfombra verde", tipo: "Mueble" },
    { id: "(F)1471", nombre: "Alfombra roja", tipo: "Mueble" },
    { id: "(F)1472", nombre: "Alfombra azul", tipo: "Mueble" },
    { id: "(F)1473", nombre: "Alfombra de patchwork", tipo: "Mueble" },
    { id: "(F)1474", nombre: "Alfombra oscura", tipo: "Mueble" },
    { id: "(F)1475", nombre: "Alfombra de hierba", tipo: "Mueble" },
    { id: "(F)1476", nombre: "Alfombra de madera", tipo: "Mueble" },
    { id: "(F)1477", nombre: "Alfombra de flores", tipo: "Mueble" },
    { id: "(F)1478", nombre: "Alfombra de escamas", tipo: "Mueble" },
    { id: "(F)1479", nombre: "Alfombra de monstruo", tipo: "Mueble" },
    { id: "(F)1480", nombre: "Alfombra de nieve", tipo: "Mueble" },
    { id: "(F)1481", nombre: "Alfombra de arena", tipo: "Mueble" },
    { id: "(F)1482", nombre: "Alfombra mística", tipo: "Mueble" },
    { id: "(F)1376", nombre: "Cuadro de naturaleza", tipo: "Mueble" },
    { id: "(F)1385", nombre: "Cuadro de granja", tipo: "Mueble" },
    { id: "(F)1386", nombre: "Cuadro de invierno", tipo: "Mueble" },
    { id: "(F)1387", nombre: "Póster de Blue City", tipo: "Mueble" },
    { id: "(F)1388", nombre: "Póster de Calico", tipo: "Mueble" },
    { id: "(F)1389", nombre: "Retrato de caballero", tipo: "Mueble" },
    { id: "(F)1394", nombre: "Estatua de búho", tipo: "Mueble" },
    { id: "(F)1395", nombre: "Estatua de piedra", tipo: "Mueble" },
    { id: "(F)1467", nombre: "Lámpara de pared pequeña", tipo: "Mueble" },
    { id: "(F)1469", nombre: "Farol de pared", tipo: "Mueble" },
    { id: "(F)1534", nombre: "Cuadro de Junimo", tipo: "Mueble" },
    { id: "(F)1535", nombre: "Cuadro de El Mago", tipo: "Mueble" },
    { id: "(F)1536", nombre: "Cuadro de El Pescador", tipo: "Mueble" },
    { id: "(F)1537", nombre: "Cuadro de El Guerrero", tipo: "Mueble" },
    { id: "(F)1538", nombre: "Mapa de la ciudad", tipo: "Mueble" },
    { id: "(F)1360", nombre: "Planta de interior grande", tipo: "Mueble" },
    { id: "(F)1361", nombre: "Planta de interior mediana", tipo: "Mueble" },
    { id: "(F)1370", nombre: "Árbol en maceta", tipo: "Mueble" },
    { id: "(F)1452", nombre: "Planta de interior 9", tipo: "Mueble" },
    { id: "(F)1453", nombre: "Planta de interior 10", tipo: "Mueble" },
    { id: "(F)1540", nombre: "Maceta de terracota", tipo: "Mueble" },
    { id: "(F)1541", nombre: "Planta de interior lujosa", tipo: "Mueble" },
    { id: "(F)1542", nombre: "Arbusto decorativo", tipo: "Mueble" },
    { id: "(F)MoreRugs:0", nombre: "Alfombra de lana blanca", tipo: "Mueble" },
    { id: "(F)MoreRugs:1", nombre: "Alfombra de lana gris", tipo: "Mueble" },
    { id: "(F)MoreRugs:2", nombre: "Alfombra de lana negra", tipo: "Mueble" },
    { id: "(F)MoreRugs:3", nombre: "Alfombra de cuadros roja", tipo: "Mueble" },
    { id: "(F)MoreRugs:4", nombre: "Alfombra de cuadros azul", tipo: "Mueble" },
    { id: "(F)MoreRugs:5", nombre: "Alfombra geométrica", tipo: "Mueble" },
    { id: "(F)MoreRugs:6", nombre: "Alfombra de hojas", tipo: "Mueble" },
    { id: "(F)MoreRugs:7", nombre: "Alfombra de sol", tipo: "Mueble" },
    { id: "(F)730", nombre: "Cesta de mimbre", tipo: "Mueble" },
    { id: "(F)733", nombre: "Caja de madera", tipo: "Mueble" },
    { id: "(F)736", nombre: "Barril de vino decorativo", tipo: "Mueble" },
    { id: "(F)1281", nombre: "Estantería de nogal", tipo: "Mueble" },
    { id: "(F)1282", nombre: "Estantería de abedul", tipo: "Mueble" },
    { id: "(F)1284", nombre: "Estantería de caoba", tipo: "Mueble" },
    { id: "(F)1286", nombre: "Estantería de invierno", tipo: "Mueble" },
    { id: "(F)1288", nombre: "Estantería clásica", tipo: "Mueble" },
    { id: "(F)1312", nombre: "Tocadiscos antiguo", tipo: "Mueble" },
    { id: "(F)1313", nombre: "Caja de música", tipo: "Mueble" },
    { id: "(F)1465", nombre: "Farol colgante", tipo: "Mueble" },
    { id: "(F)1550", nombre: "Estatua de H.M.", tipo: "Mueble" },
    { id: "(F)1551", nombre: "Estatua de Iridium", tipo: "Mueble" },
    { id: "(F)2000", nombre: "Cama individual", tipo: "Mueble" },
    { id: "(F)2001", nombre: "Cama individual de abedul", tipo: "Mueble" },
    { id: "(F)2002", nombre: "Cama individual de roble", tipo: "Mueble" },
    { id: "(F)2003", nombre: "Cama individual de nogal", tipo: "Mueble" },
    { id: "(F)2004", nombre: "Cama individual de caoba", tipo: "Mueble" },
    { id: "(F)2005", nombre: "Cama individual moderna", tipo: "Mueble" },
    { id: "(F)2006", nombre: "Cama individual azul", tipo: "Mueble" },
    { id: "(F)2007", nombre: "Cama individual rosa", tipo: "Mueble" },
    { id: "(F)2008", nombre: "Cama individual de invierno", tipo: "Mueble" },
    { id: "(F)2009", nombre: "Cama individual tropical", tipo: "Mueble" },
    { id: "(F)2039", nombre: "Cama doble", tipo: "Mueble" },
    { id: "(F)2040", nombre: "Cama doble de abedul", tipo: "Mueble" },
    { id: "(F)2041", nombre: "Cama doble de roble", tipo: "Mueble" },
    { id: "(F)2042", nombre: "Cama doble de nogal", tipo: "Mueble" },
    { id: "(F)2043", nombre: "Cama doble de caoba", tipo: "Mueble" },
    { id: "(F)2044", nombre: "Cama doble moderna", tipo: "Mueble" },
    { id: "(F)2045", nombre: "Cama doble azul", tipo: "Mueble" },
    { id: "(F)2046", nombre: "Cama doble rosa", tipo: "Mueble" },
    { id: "(F)2047", nombre: "Cama doble de invierno", tipo: "Mueble" },
    { id: "(F)2048", nombre: "Cama doble tropical", tipo: "Mueble" },
    { id: "(F)2078", nombre: "Cama de matrimonio", tipo: "Mueble" },
    { id: "(F)2079", nombre: "Cama de matrimonio de abedul", tipo: "Mueble" },
    { id: "(F)2080", nombre: "Cama de matrimonio de roble", tipo: "Mueble" },
    { id: "(F)2081", nombre: "Cama de matrimonio de nogal", tipo: "Mueble" },
    { id: "(F)2082", nombre: "Cama de matrimonio de caoba", tipo: "Mueble" },
    { id: "(F)2083", nombre: "Cama de matrimonio moderna", tipo: "Mueble" },
    { id: "(F)2084", nombre: "Cama de matrimonio azul", tipo: "Mueble" },
    { id: "(F)2085", nombre: "Cama de matrimonio rosa", tipo: "Mueble" },
    { id: "(F)2086", nombre: "Cama de matrimonio de invierno", tipo: "Mueble" },
    { id: "(F)2087", nombre: "Cama de matrimonio tropical", tipo: "Mueble" },
    { id: "(F)2095", nombre: "Cama de matrimonio de lujo", tipo: "Mueble" },
    { id: "(F)2096", nombre: "Cama de matrimonio pirata", tipo: "Mueble" },
    { id: "(F)2097", nombre: "Cama de matrimonio de estrella", tipo: "Mueble" },
    { id: "(F)1614", nombre: "Chimenea de ladrillo", tipo: "Mueble" },
    { id: "(F)1615", nombre: "Chimenea de piedra", tipo: "Mueble" },
    { id: "(F)1616", nombre: "Chimenea moderna", tipo: "Mueble" },
    { id: "(F)1617", nombre: "Chimenea de hierro", tipo: "Mueble" },
    { id: "(F)1618", nombre: "Chimenea majestuosa", tipo: "Mueble" },
    { id: "(F)1742", nombre: "Ventana pequeña", tipo: "Mueble" },
    { id: "(F)1743", nombre: "Ventana de madera", tipo: "Mueble" },
    { id: "(F)1745", nombre: "Ventana grande", tipo: "Mueble" },
    { id: "(F)1747", nombre: "Ventana con vistas al mar", tipo: "Mueble" },
    { id: "(F)1750", nombre: "Ventana de ojo de buey", tipo: "Mueble" },
    { id: "(F)1320", nombre: "Peluche de Junimo", tipo: "Mueble" },
    { id: "(F)1322", nombre: "Estatua de la fortuna", tipo: "Mueble" },
    { id: "(F)1324", nombre: "Estatua de protección", tipo: "Mueble" },
    { id: "(F)1326", nombre: "Huevo de pascua decorativo", tipo: "Mueble" },

    //Categoría de Paredes
    { id: "(WP)0", nombre: "Papel de rayas amarillas", tipo: "Pared" },
    { id: "(WP)1", nombre: "Papel de playa y palmeras", tipo: "Pared" },
    { id: "(WP)2", nombre: "Papel de acuario", tipo: "Pared" },
    { id: "(WP)3", nombre: "Papel de estrellas nocturnas", tipo: "Pared" },
    { id: "(WP)4", nombre: "Papel de noche estrellada", tipo: "Pared" },
    { id: "(WP)5", nombre: "Papel de lava", tipo: "Pared" },
    { id: "(WP)6", nombre: "Papel de desierto", tipo: "Pared" },
    { id: "(WP)7", nombre: "Papel de corazones rosa", tipo: "Pared" },
    { id: "(WP)8", nombre: "Papel de baldosas verdes", tipo: "Pared" },
    { id: "(WP)9", nombre: "Papel de paisaje rural", tipo: "Pared" },
    { id: "(WP)10", nombre: "Papel de nubes rosa", tipo: "Pared" },
    { id: "(WP)11", nombre: "Papel de paneles de madera", tipo: "Pared" },
    { id: "(WP)12", nombre: "Papel de ladrillo gris", tipo: "Pared" },
    { id: "(WP)13", nombre: "Papel de montaña lila", tipo: "Pared" },
    { id: "(WP)14", nombre: "Papel de espacio profundo", tipo: "Pared" },
    { id: "(WP)15", nombre: "Papel de colinas soleadas", tipo: "Pared" },
    { id: "(WP)16", nombre: "Papel de burbujas azules", tipo: "Pared" },
    { id: "(WP)17", nombre: "Papel de confeti", tipo: "Pared" },
    { id: "(WP)18", nombre: "Papel de tablones marrones", tipo: "Pared" },
    { id: "(WP)19", nombre: "Papel de ladrillo rojo", tipo: "Pared" },
    { id: "(WP)20", nombre: "Papel de cielo azul", tipo: "Pared" },
    { id: "(WP)21", nombre: "Papel de rayas azules", tipo: "Pared" },
    { id: "(WP)22", nombre: "Papel de ladrillo naranja", tipo: "Pared" },
    { id: "(WP)23", nombre: "Papel de bosque oscuro", tipo: "Pared" },
    { id: "(WP)24", nombre: "Papel de hojas verdes", tipo: "Pared" },
    { id: "(WP)25", nombre: "Papel de peces", tipo: "Pared" },
    { id: "(WP)26", nombre: "Papel de ciudad nocturna", tipo: "Pared" },
    { id: "(WP)27", nombre: "Papel azul liso", tipo: "Pared" },
    { id: "(WP)28", nombre: "Papel de franjas amarillas", tipo: "Pared" },
    { id: "(WP)29", nombre: "Papel de jardín verde", tipo: "Pared" },
    { id: "(WP)30", nombre: "Papel de espacio lila", tipo: "Pared" },
    { id: "(WP)31", nombre: "Papel de cueva con setas", tipo: "Pared" },
    { id: "(WP)32", nombre: "Papel de gotas de agua", tipo: "Pared" },
    { id: "(WP)33", nombre: "Papel de atardecer naranja", tipo: "Pared" },
    { id: "(WP)34", nombre: "Papel rosa liso", tipo: "Pared" },
    { id: "(WP)35", nombre: "Papel de nubes lila", tipo: "Pared" },
    { id: "(WP)36", nombre: "Papel de lunas amarillas", tipo: "Pared" },
    { id: "(WP)37", nombre: "Papel de tréboles", tipo: "Pared" },
    { id: "(WP)38", nombre: "Papel de cielo brillante", tipo: "Pared" },
    { id: "(WP)39", nombre: "Papel de estantería roja", tipo: "Pared" },
    { id: "(WP)40", nombre: "Papel de rombos verdes", tipo: "Pared" },
    { id: "(WP)41", nombre: "Papel de madera rústica", tipo: "Pared" },
    { id: "(WP)42", nombre: "Papel de noche azul", tipo: "Pared" },
    { id: "(WP)43", nombre: "Papel de flores rosas", tipo: "Pared" },
    { id: "(WP)44", nombre: "Papel gris liso", tipo: "Pared" },
    { id: "(WP)45", nombre: "Papel de cielo con nubes", tipo: "Pared" },
    { id: "(WP)46", nombre: "Papel de galaxia lila", tipo: "Pared" },
    { id: "(WP)47", nombre: "Papel de esqueleto", tipo: "Pared" },
    { id: "(WP)48", nombre: "Papel verde liso", tipo: "Pared" },
    { id: "(WP)49", nombre: "Papel rosa claro liso", tipo: "Pared" },
    { id: "(WP)50", nombre: "Papel azul claro liso", tipo: "Pared" },
    { id: "(WP)51", nombre: "Papel naranja liso", tipo: "Pared" },
    { id: "(WP)52", nombre: "Papel amarillo liso", tipo: "Pared" },
    { id: "(WP)53", nombre: "Papel rojo liso", tipo: "Pared" },
    { id: "(WP)54", nombre: "Papel verde bosque liso", tipo: "Pared" },
    { id: "(WP)55", nombre: "Papel de paneles japoneses", tipo: "Pared" },
    { id: "(WP)56", nombre: "Papel de rejilla negra", tipo: "Pared" },
    { id: "(WP)57", nombre: "Papel de paneles crema", tipo: "Pared" },
    { id: "(WP)58", nombre: "Papel de entramado marrón", tipo: "Pared" },
    { id: "(WP)59", nombre: "Papel marrón oscuro liso", tipo: "Pared" },
    { id: "(WP)60", nombre: "Papel de llamas", tipo: "Pared" },
    { id: "(WP)61", nombre: "Papel amarillo brillante", tipo: "Pared" },
    { id: "(WP)62", nombre: "Papel de bambú", tipo: "Pared" },
    { id: "(WP)63", nombre: "Papel de madera noble", tipo: "Pared" },
    { id: "(WP)64", nombre: "Papel azul real", tipo: "Pared" },
    { id: "(WP)65", nombre: "Papel de ladrillo blanco", tipo: "Pared" },
    { id: "(WP)66", nombre: "Papel de ladrillo pastel", tipo: "Pared" },
    { id: "(WP)67", nombre: "Papel crema liso", tipo: "Pared" },
    { id: "(WP)68", nombre: "Papel celeste liso", tipo: "Pared" },
    { id: "(WP)69", nombre: "Papel degradado lila", tipo: "Pared" },
    { id: "(WP)70", nombre: "Papel degradado verde", tipo: "Pared" },
    { id: "(WP)71", nombre: "Papel amarillo pálido liso", tipo: "Pared" },
    { id: "(WP)72", nombre: "Papel coral liso", tipo: "Pared" },
    { id: "(WP)73", nombre: "Papel lila claro liso", tipo: "Pared" },
    { id: "(WP)74", nombre: "Papel verde menta liso", tipo: "Pared" },
    { id: "(WP)75", nombre: "Papel beige liso", tipo: "Pared" },
    { id: "(WP)76", nombre: "Papel granate liso", tipo: "Pared" },
    { id: "(WP)77", nombre: "Papel violeta liso", tipo: "Pared" },
    { id: "(WP)78", nombre: "Papel verde oscuro liso", tipo: "Pared" },
    { id: "(WP)79", nombre: "Papel de pradera", tipo: "Pared" },
    { id: "(WP)80", nombre: "Papel gris carbón liso", tipo: "Pared" },
    { id: "(WP)81", nombre: "Papel azul grisáceo liso", tipo: "Pared" },
    { id: "(WP)82", nombre: "Papel de colinas verdes", tipo: "Pared" },
    { id: "(WP)83", nombre: "Papel de piedra gris", tipo: "Pared" },
    { id: "(WP)84", nombre: "Papel de rayas rosas", tipo: "Pared" },
    { id: "(WP)85", nombre: "Papel de rayas verdes", tipo: "Pared" },
    { id: "(WP)86", nombre: "Papel de columna clásica", tipo: "Pared" },
    { id: "(WP)87", nombre: "Papel de baldosas turquesa", tipo: "Pared" },
    { id: "(WP)88", nombre: "Papel de mimbre", tipo: "Pared" },
    { id: "(WP)89", nombre: "Papel de rombos amarillos", tipo: "Pared" },
    { id: "(WP)90", nombre: "Papel de cielo lila", tipo: "Pared" },
    { id: "(WP)91", nombre: "Papel lila liso", tipo: "Pared" },
    { id: "(WP)92", nombre: "Papel de cactus", tipo: "Pared" },
    { id: "(WP)93", nombre: "Papel gris oscuro liso", tipo: "Pared" },
    { id: "(WP)94", nombre: "Papel de estrellas lila", tipo: "Pared" },
    { id: "(WP)95", nombre: "Papel de paneles de caoba", tipo: "Pared" },
    { id: "(WP)96", nombre: "Papel de motas de colores", tipo: "Pared" },
    { id: "(WP)97", nombre: "Papel blanco liso", tipo: "Pared" },
    { id: "(WP)98", nombre: "Papel de madera rústica vertical", tipo: "Pared" },
    { id: "(WP)99", nombre: "Papel de cuadros rosas", tipo: "Pared" },
    { id: "(WP)100", nombre: "Papel de rayas verde claro", tipo: "Pared" },
    { id: "(WP)101", nombre: "Papel de rombos rosa", tipo: "Pared" },
    { id: "(WP)102", nombre: "Papel verde agua liso", tipo: "Pared" },
    { id: "(WP)103", nombre: "Papel marrón rosado liso", tipo: "Pared" },
    { id: "(WP)104", nombre: "Papel de cortinas amarillas", tipo: "Pared" },
    { id: "(WP)105", nombre: "Papel de cortinas grises", tipo: "Pared" },
    { id: "(WP)106", nombre: "Papel azul intenso liso", tipo: "Pared" },
    { id: "(WP)107", nombre: "Papel de noche estrellada azul", tipo: "Pared" },
    { id: "(WP)108", nombre: "Papel de vidrieras", tipo: "Pared" },
    { id: "(WP)109", nombre: "Papel terracota liso", tipo: "Pared" },
    { id: "(WP)110", nombre: "Papel de mandarina", tipo: "Pared" },
    { id: "(WP)111", nombre: "Papel de rayas lila", tipo: "Pared" },
    { id: "(WP)MoreWalls:0", nombre: "Papel de corazones lila", tipo: "Pared" },
    { id: "(WP)MoreWalls:1", nombre: "Papel de soles amarillos", tipo: "Pared" },
    { id: "(WP)MoreWalls:2", nombre: "Papel de puntos blancos sobre amarillo", tipo: "Pared" },
    { id: "(WP)MoreWalls:3", nombre: "Papel de manzanas rojas", tipo: "Pared" },
    { id: "(WP)MoreWalls:4", nombre: "Papel de montañas azules", tipo: "Pared" },
    { id: "(WP)MoreWalls:5", nombre: "Papel rojo real", tipo: "Pared" },
    { id: "(WP)MoreWalls:6", nombre: "Papel de bosque pino", tipo: "Pared" },
    { id: "(WP)MoreWalls:7", nombre: "Papel de burbujas azul vivo", tipo: "Pared" },
    { id: "(WP)MoreWalls:8", nombre: "Papel de cascada azul", tipo: "Pared" },
    { id: "(WP)MoreWalls:9", nombre: "Papel de paneles de madera oscura", tipo: "Pared" },
    { id: "(WP)MoreWalls:10", nombre: "Papel de espacio místico", tipo: "Pared" },
    { id: "(WP)MoreWalls:11", nombre: "Papel de lunas sobre azul", tipo: "Pared" },
    { id: "(WP)MoreWalls:12", nombre: "Papel de madera tallada", tipo: "Pared" },
    { id: "(WP)MoreWalls:13", nombre: "Papel de tótems de madera", tipo: "Pared" },
    { id: "(WP)MoreWalls:14", nombre: "Papel de piña", tipo: "Pared" },
    { id: "(WP)MoreWalls:15", nombre: "Papel de tablones de bosque", tipo: "Pared" },
    { id: "(WP)MoreWalls:16", nombre: "Papel rojo ornamental", tipo: "Pared" },
    { id: "(WP)MoreWalls:17", nombre: "Papel de cuadros marrones", tipo: "Pared" },
    { id: "(WP)MoreWalls:18", nombre: "Papel de ondas naranja", tipo: "Pared" },
    { id: "(WP)MoreWalls:19", nombre: "Papel festivo rojo", tipo: "Pared" },
    { id: "(WP)MoreWalls:20", nombre: "Papel de ventana al cielo", tipo: "Pared" },
    { id: "(WP)MoreWalls:21", nombre: "Papel de piedra negra labrada", tipo: "Pared" },
    { id: "(WP)MoreWalls:22", nombre: "Papel de encaje lila", tipo: "Pared" },
    { id: "(WP)MoreWalls:23", nombre: "Papel ornamental naranja", tipo: "Pared" },
    { id: "(WP)MoreWalls:24", nombre: "Papel de bosque invernal lila", tipo: "Pared" },
    { id: "(WP)MoreWalls:25", nombre: "Papel de ondas violeta", tipo: "Pared" },

    // Categoría de Pisos
    { id: "(FL)0", nombre: "Piso de madera", tipo: "Piso" },
    { id: "(FL)1", nombre: "Piso de madera rústico", tipo: "Piso" },
    { id: "(FL)2", nombre: "Piso de tablones", tipo: "Piso" },
    { id: "(FL)3", nombre: "Piso de madera clara", tipo: "Piso" },
    { id: "(FL)4", nombre: "Piso de madera oscura", tipo: "Piso" },
    { id: "(FL)5", nombre: "Piso de madera rojiza", tipo: "Piso" },
    { id: "(FL)6", nombre: "Piso de baldosas", tipo: "Piso" },
    { id: "(FL)7", nombre: "Piso de piedra", tipo: "Piso" },
    { id: "(FL)8", nombre: "Piso de mosaico azul", tipo: "Piso" },
    { id: "(FL)9", nombre: "Piso de parqué", tipo: "Piso" },
    { id: "(FL)10", nombre: "Piso de ladrillo", tipo: "Piso" },
    { id: "(FL)11", nombre: "Piso de adobe", tipo: "Piso" },
    { id: "(FL)12", nombre: "Piso de piedra violeta", tipo: "Piso" },
    { id: "(FL)13", nombre: "Piso de madera naranja", tipo: "Piso" },
    { id: "(FL)14", nombre: "Piso de baldosas blancas", tipo: "Piso" },
    { id: "(FL)15", nombre: "Piso azulado", tipo: "Piso" },
    { id: "(FL)16", nombre: "Piso de caoba", tipo: "Piso" },
    { id: "(FL)17", nombre: "Piso de paneles", tipo: "Piso" },
    { id: "(FL)18", nombre: "Piso de roble", tipo: "Piso" },
    { id: "(FL)19", nombre: "Piso de madera de cebra", tipo: "Piso" },
    { id: "(FL)20", nombre: "Piso de corcho", tipo: "Piso" },
    { id: "(FL)21", nombre: "Piso de madera rayado", tipo: "Piso" },
    { id: "(FL)22", nombre: "Piso de baldosas de cristal", tipo: "Piso" },
    { id: "(FL)23", nombre: "Piso de terracota", tipo: "Piso" },
    { id: "(FL)24", nombre: "Piso de crema", tipo: "Piso" },
    { id: "(FL)25", nombre: "Piso azul brillante", tipo: "Piso" },
    { id: "(FL)26", nombre: "Piso de ladrillo gastado", tipo: "Piso" },
    { id: "(FL)27", nombre: "Piso de hierba", tipo: "Piso" },
    { id: "(FL)28", nombre: "Piso de jardín verde", tipo: "Piso" },
    { id: "(FL)29", nombre: "Piso de terracota rojizo", tipo: "Piso" },
    { id: "(FL)30", nombre: "Piso de piedra gris", tipo: "Piso" },
    { id: "(FL)31", nombre: "Piso de mármol blanco", tipo: "Piso" },
    { id: "(FL)32", nombre: "Piso de madera de cerezo", tipo: "Piso" },
    { id: "(FL)33", nombre: "Piso de madera miel", tipo: "Piso" },
    { id: "(FL)34", nombre: "Piso de madera moca", tipo: "Piso" },
    { id: "(FL)35", nombre: "Piso de corcho claro", tipo: "Piso" },
    { id: "(FL)36", nombre: "Piso azul noche", tipo: "Piso" },
    { id: "(FL)37", nombre: "Piso de baldosa blanca pura", tipo: "Piso" },
    { id: "(FL)38", nombre: "Piso de asfalto", tipo: "Piso" },
    { id: "(FL)39", nombre: "Piso de piedra oscuro", tipo: "Piso" },
    { id: "(FL)40", nombre: "Piso de arcilla", tipo: "Piso" },
    { id: "(FL)41", nombre: "Piso de madera rústico oscuro", tipo: "Piso" },
    { id: "(FL)42", nombre: "Piso de madera naranja claro", tipo: "Piso" },
    { id: "(FL)43", nombre: "Piso de bosque", tipo: "Piso" },
    { id: "(FL)44", nombre: "Piso oceánico", tipo: "Piso" },
    { id: "(FL)45", nombre: "Piso de piedra pizarra", tipo: "Piso" },
    { id: "(FL)46", nombre: "Piso gris azulado", tipo: "Piso" },
    { id: "(FL)47", nombre: "Piso de baldosas celestes", tipo: "Piso" },
    { id: "(FL)48", nombre: "Piso rosa pastel", tipo: "Piso" },
    { id: "(FL)49", nombre: "Piso verde esmeralda", tipo: "Piso" },
    { id: "(FL)50", nombre: "Piso de madera nogal", tipo: "Piso" },
    { id: "(FL)51", nombre: "Piso de cemento", tipo: "Piso" },
    { id: "(FL)52", nombre: "Piso de madera de pino", tipo: "Piso" },
    { id: "(FL)53", nombre: "Piso de madera ceniza", tipo: "Piso" },
    { id: "(FL)54", nombre: "Piso de madera grisáceo", tipo: "Piso" },
    { id: "(FL)55", nombre: "Piso rosa chicle", tipo: "Piso" },
    { id: "(FL)56", nombre: "Piso de madera canela", tipo: "Piso" },
    { id: "(FL)57", nombre: "Piso de musgo", tipo: "Piso" },
    { id: "(FL)58", nombre: "Piso de piedra volcánica", tipo: "Piso" },
    { id: "(FL)59", nombre: "Piso granate", tipo: "Piso" },
    { id: "(FL)60", nombre: "Piso de piedra negra", tipo: "Piso" },
    { id: "(FL)61", nombre: "Piso gris oscuro", tipo: "Piso" },
    { id: "(FL)62", nombre: "Piso de grava", tipo: "Piso" },
    { id: "(FL)63", nombre: "Piso de piedra lisa", tipo: "Piso" },
    { id: "(FL)64", nombre: "Piso rosa vibrante", tipo: "Piso" },
    { id: "(FL)65", nombre: "Piso de carbón", tipo: "Piso" },
    { id: "(FL)66", nombre: "Piso de madera quemada", tipo: "Piso" },
    { id: "(FL)67", nombre: "Piso lila oscuro", tipo: "Piso" },
    { id: "(FL)68", nombre: "Piso de amatista", tipo: "Piso" },
    { id: "(FL)69", nombre: "Piso de madera rojizo oscuro", tipo: "Piso" },
    { id: "(FL)70", nombre: "Piso de madera curtida", tipo: "Piso" },
    { id: "(FL)71", nombre: "Piso naranja zanahoria", tipo: "Piso" },
    { id: "(FL)72", nombre: "Piso de mármol rosado", tipo: "Piso" },
    { id: "(FL)73", nombre: "Piso de arena", tipo: "Piso" },
    { id: "(FL)74", nombre: "Piso de coral", tipo: "Piso" },
    { id: "(FL)75", nombre: "Piso violeta claro", tipo: "Piso" },
    { id: "(FL)76", nombre: "Piso de menta", tipo: "Piso" },
    { id: "(FL)77", nombre: "Piso de madera gris claro", tipo: "Piso" },
    { id: "(FL)78", nombre: "Piso de mosaico celeste", tipo: "Piso" },
    { id: "(FL)79", nombre: "Piso de cuadros rosas", tipo: "Piso" },
    { id: "(FL)80", nombre: "Piso melocotón", tipo: "Piso" },
    { id: "(FL)81", nombre: "Piso rojo suave", tipo: "Piso" },
    { id: "(FL)82", nombre: "Piso rosa pastel", tipo: "Piso" },
    { id: "(FL)83", nombre: "Piso de madera pálida", tipo: "Piso" },
    { id: "(FL)84", nombre: "Piso café", tipo: "Piso" },
    { id: "(FL)85", nombre: "Piso verde oliva", tipo: "Piso" },
    { id: "(FL)86", nombre: "Piso de burbujas", tipo: "Piso" },
    { id: "(FL)87", nombre: "Piso crema suave", tipo: "Piso" },
    { id: "(FL)MoreFloors:0", nombre: "Piso de madera oscuro liso", tipo: "Piso" },
    { id: "(FL)MoreFloors:1", nombre: "Piso de madera granate liso", tipo: "Piso" },
    { id: "(FL)MoreFloors:2", nombre: "Piso de madera canela liso", tipo: "Piso" },
    { id: "(FL)MoreFloors:3", nombre: "Piso de madera arcilla liso", tipo: "Piso" },
    { id: "(FL)MoreFloors:4", nombre: "Piso de piedra verde oscuro", tipo: "Piso" },
    { id: "(FL)MoreFloors:5", nombre: "Piso de madera chocolate liso", tipo: "Piso" },
    { id: "(FL)MoreFloors:6", nombre: "Piso de piedra gris oscuro liso", tipo: "Piso" },
    { id: "(FL)MoreFloors:7", nombre: "Piso de madera ocre liso", tipo: "Piso" },
    { id: "(FL)MoreFloors:8", nombre: "Piso de piedra azul noche", tipo: "Piso" },
];

const listaVisual = document.getElementById("listaVisual");
const inputFiltro = document.getElementById("filtro");

function cargarItems(items) {
    if (!listaVisual) return;
    listaVisual.innerHTML = ""; 

    items.forEach(item => {
        const li = document.createElement("li");
        li.innerHTML = `
            <span class="item-id">[${item.id}]</span>
            <span class="item-nombre"> - ${item.nombre}</span>
            <button class="btn-copy-corner" onclick="copiarID('${item.id}')" title="Copiar ID">
                <img src="https://cdn-icons-png.flaticon.com/512/1621/1621635.png" alt="copy">
            </button>
            <span class="tag-tipo">${item.tipo}</span>
        `;
        listaVisual.appendChild(li);
    });
}

function copiarID(id) {
    const textoACopiar = "[" + id + "]";
    navigator.clipboard.writeText(textoACopiar).then(() => {
        console.log("Copiado: " + textoACopiar);
    }).catch(err => {
        console.error("Error: ", err);
    });
}

function filtrar() {
    const busqueda = inputFiltro.value.toLowerCase();
    const filtrados = dbItems.filter(item => 
        item.nombre.toLowerCase().includes(busqueda) || 
        item.id.toString().toLowerCase().includes(busqueda)
    );
    cargarItems(filtrados);
}

function filtrarPorClase(categoriaSeleccionada) {
    if (categoriaSeleccionada === 'Todos') {
        cargarItems(dbItems);
    } else {
        const filtrados = dbItems.filter(item => item.tipo === categoriaSeleccionada);
        cargarItems(filtrados);
    }
    inputFiltro.value = ""; 
}

function toggleDarkMode() {
    document.body.classList.toggle("dark-theme");
}

window.onload = () => {
    if (typeof dbItems !== 'undefined') {
        cargarItems(dbItems);
    } else {
        console.error("dbItems no definido.");
    }
};
